### ISSUE TITLE
Evaluate migration of images from Upshift central repository to some other location.

### ISSUE THREAD

**Issue by tumido** [thoth-station/jupyternb-build-pipeline#2]
_Follow up to an email thread_

We may need to consider migration of our produced images from the internal Upshift repository to somewhere else. Mind that the produced images may contain sensitive internal data, so they can't land on public Quay repos.

### Reference

```
Hi All,
Thanks for your input so far.  I have added responses in red below.

Maneesh Mehra (CVP):  Thanks for bringing this to the CVP team's attention. We currently use this registry to store our sanity tests image. I have opened https://projects.engineering.redhat.com/browse/CVP-1184 for the CVP team to work on this migration. Do you want to give us a sense of urgency on this ?
Ideally by the end of September 2020, and definitely by the end of December 2020.  

Mike Bonnet (ic3):  We have internal images that are not suitable for public repos. Is there a process for requesting private quay.io repos? Is there guidance about creating a new org, or using an existing one? Note that the current "redhat" org is no longer available for general use.
We have some notes/guidelines that we can update and then point you to.

Mark Eastman (QE):  Pavel may have more details than I but we use these systems to test software before it is released so I am not sure if we can push the images to quay.io during the test phases.
We will look to see if there are other registries at Red Hat that are not in Production, that folks could use.

Regards,
Jeff
```

```
Hi Teams,
We are having challenges maintaining the centralized registry with our current capacity.  This central registry at docker-registry.upshift.redhat.com is not a production service, and has low/no SLA.  Going forward, we recommend using quay.io for critical workflows.  If using quay.io is not possible, can you tell us why it is not possible for your team?  In addition, if using quay.io is not possible, what would you suggest as requirements for an 'internal' central registry?

Thanks,
Jeff
```

**Comment by tumido** [comment]
cc @harshad16 @4n4nd

**Comment by 4n4nd** [comment]
i think the issue will be with setting up credentials to access from private quay repos and updating every image inside Internal DataHub

**Comment by harshad16** [comment]
can we get private organization on quay.io ? as a normal organization gets one free private repository, if we can get an organization that can have private repositories, we can set up a bot on quay.io repo and that would help us in the push and pull of the image.

**Comment by tumido** [comment]
@durandom @goern do we have any Quay orgs with private repos in AICoE available as of now? Private repos are not for free with Quay. We might end up spending some :dollar: :moneybag:  

https://quay.io/organizations/new/

![image](https://user-images.githubusercontent.com/7453394/87555698-195b9000-c6b6-11ea-8158-2be1e0ee37a2.png)

**Comment by goern** [comment]
Well, we have redhat as a private org on quay, but this comes with a lot of requirements...

would we go with a micro plan?
